version: '2'

services:
  database:
    image: mysql:5.7
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: 'toor'
      MYSQL_USER: 'tasks'
      MYSQL_PASSWORD: 'taskstasks'
      MYSQL_DATABASE: 'tasks'

  migrate:
    build: api/
    command: './docker-migrate.sh'

    depends_on:
      - database
    environment:
      SECRET_KEY: 'local-docker-secret'
      DATABASE_URL: 'mysql://tasks:taskstasks@database:3306/tasks'
      DATABASE_HOST: 'database'
      DATABASE_PORT: '3306'

  api:
    build:  api/
    depends_on:
      - database
      - migrate
    links:
      - database:database
    ports:
      - 80
    environment:
      SECRET_KEY: 'local-docker-secret'
      DATABASE_URL: 'mysql://tasks:taskstasks@database:3306/tasks'
      DATABASE_HOST: 'database'
      DATABASE_PORT: '3306'

      FAKE_DATA: "yes"

  ui:
    build:  ui/

  frontend:
    image: nginx:stable-alpine
    ports:
      - 9001:80
    links:
      - ui
      - api

    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf:ro
